<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="well col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <address>
                        <h4>BITS-INFOTECH</h4>
                      
                            1B Smart Tower, Kanpur<br>
                            Lucknow Rd, Sector G, LDA Colony,<br>
                            Lucknow, Uttar Pradesh 226012
                        
                            <abbr title="Phone">P:</abbr>8976110254
                    </address>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    <p>
                        <em>Date: {{$transaction[0]->date}}</em>
                    </p>
                    <p>
                        <em>Receipt #: {{$transaction[0]->id}}</em>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="text-center">
                    <h1>Receipt</h1>
                </div>
                </span>
                <table class="table table-hover">
                   
                    <tbody>
                        <tr>
                            <td  colspan="2">
                                <strong>Student :</strong> <em>{{$transaction[0]->getStudent->name}}</em></h4>
                            </td>
                           
                        </tr>
                   
                        <tr>
                            <td  colspan="2">
                                <strong>Student :</strong> <em>{{$transaction[0]->getCourse->name}}</em></h4>
                            </td>
                          
                        </tr>
                       
                        <tr>
                            <td class="text-center">
                                <p>
                                    <img src="{{url('upload/stamp.jpg')}}" height="100" width="100" alt="">
                                </p>
                               
                            </td>
                            <td class="text-right">
                                <h4><strong>Paid Fees: </strong></h4>
                            </td>
                            <td class="text-center text-danger">
                                <h4><strong>{{$transaction[0]->amount}}</strong></h4>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <button onclick="window.print();" type="button" class="btn btn-success btn-lg btn-block">
                    Download Invoice <span class="glyphicon glyphicon-chevron-right"></span>
                </button></td>
                <div> <strong>Note: </strong> This invoice is generated by computer, verification stamp of institute required.</div>
                <div class="text-danger"> <strong >Note: </strong> Given amount is not refundable. </div>
            </div>
        </div>
    </div>
